// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using WeddingInvitations.Api.Data;

#nullable disable

namespace WeddingInvitations.Api.Migrations
{
    [DbContext(typeof(WeddingDbContext))]
    [Migration("20250722015850_MakeEmailOptional")]
    partial class MakeEmailOptional
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.35")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("WeddingInvitations.Api.Models.Family", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<bool?>("Attending")
                        .HasColumnType("boolean");

                    b.Property<string>("CivilAddress")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("CivilDateTime")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("CivilVenue")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("ConfirmedGuests")
                        .HasColumnType("integer");

                    b.Property<string>("ContactPerson")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("DietaryRestrictions")
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)");

                    b.Property<string>("Email")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<string>("FamilyName")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<bool>("FormCompleted")
                        .HasColumnType("boolean");

                    b.Property<DateTime?>("FormCompletedDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("InvitationCode")
                        .IsRequired()
                        .HasMaxLength(8)
                        .HasColumnType("character varying(8)");

                    b.Property<bool>("InvitationSent")
                        .HasColumnType("boolean");

                    b.Property<bool>("InvitationViewed")
                        .HasColumnType("boolean");

                    b.Property<DateTime?>("LastReminderSent")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("MaxGuests")
                        .HasColumnType("integer");

                    b.Property<string>("Phone")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<string>("ReceptionAddress")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("ReceptionDateTime")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("ReceptionVenue")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("ReligiousAddress")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("ReligiousDateTime")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("ReligiousVenue")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("ReminderCount")
                        .HasColumnType("integer");

                    b.Property<bool>("Responded")
                        .HasColumnType("boolean");

                    b.Property<DateTime?>("ResponseDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime>("ResponseDeadline")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime?>("SentDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("SpecialMessage")
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime?>("ViewedDate")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("Email")
                        .IsUnique();

                    b.HasIndex("InvitationCode")
                        .IsUnique();

                    b.ToTable("Families");
                });

            modelBuilder.Entity("WeddingInvitations.Api.Models.Guest", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Age")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("DietaryRestrictions")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<int>("FamilyId")
                        .HasColumnType("integer");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.HasKey("Id");

                    b.HasIndex("FamilyId");

                    b.ToTable("Guests");
                });

            modelBuilder.Entity("WeddingInvitations.Api.Models.Guest", b =>
                {
                    b.HasOne("WeddingInvitations.Api.Models.Family", "Family")
                        .WithMany("Guests")
                        .HasForeignKey("FamilyId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Family");
                });

            modelBuilder.Entity("WeddingInvitations.Api.Models.Family", b =>
                {
                    b.Navigation("Guests");
                });
#pragma warning restore 612, 618
        }
    }
}
